name: New Environment
color: null
values:
  - key: baseUrl
    value: https://jsonplaceholder.typicode.com
    enabled: true
    description: ""
  - key: accessToken
    value: ""
    enabled: true
    description: ""
  - key: apiKey
    value: ""
    enabled: true
    description: ""
  - key: createdPostId
    value: ""
    enabled: true
