@startuml
skinparam shadowing true

title Процесс создания страницы бренда

|Инициатор|
start
:Составить концепцию по новому бренду;
:Отправить концепцию на согласование;
|Директор развития категории одежда|
:Пришел запрос на согласование;
:Рассмотреть концепцию;
if (Концепция согласована?) then (Нет)
    #pink :Отправить отказ;
    |Инициатор|
    #pink :Получен отказ;
    stop
else (Да)
    |Директор развития категории одежда|
    #palegreen :Отправить согласование;
    |Инициатор|
    #palegreen :Получено согласование;
    :Отправить согласованную заявку на добавление бренда;
    |Контент-менеджер|
    :Получена согласованная заявка;
    :Создать страницу нового бренда на тестовом контуре;
    note right: отдельный подпроцесс согласования вида страницы с инициатором
    :Создать страницу нового бренда в продовой среде;
    stop
endif
@enduml