@startuml

Actor "Пользователь" as client
participant "Front" as front
participant "checkout-service" as back1
database "Database" as db

autonumber
activate client
client -> front: Клиент добавляет\n товар в корзину
activate front
front -> back1: Запрос на добавление в корзину\n POST /api/v1/checkout-service/products/add
activate back1
back1 -> db: Запись в БД на\n добавление товара\n в корзину по id
activate db
alt Произошла ошибка на уровне БД
back1 <-- db: Ошибка в операции записи
front <-- back1: 200 ОК внутрення ошибка
client <-- front: Отображение уведомления\n "Произошла ошибка. Ваш\n товар не добавлен.\n Попробуйте еще раз."
else  Запись в БД успешна
back1 <-- db: Запись совершена успешно
deactivate db
front <-- back1: 200 ОК с id и названием товара
deactivate back1
client <-- front: Отображение уведомления\n "Товар X успешно добавлен."
deactivate front
deactivate client
end

@enduml