@startuml
'https://plantuml.com/activity-diagram-beta

title Джоба для проверки расчета \n срока доставки и \n отправки заказа в работу

start
:Старт каждый день в \n00:30 по Москве(UTC+3);
:Выбрать все записи
со status==CALCULATED;

repeat
:Сформировать тело запроса.
Маппинг:
    value.routesUid = directions.routesUid
    value.isActive = directions.is_active
    value.logObjectStart.objectId = directions.object_id_start
    value.logObjectStart.timezone = directions.timezone_start
    value.logObjectEnd.objectId= directions.object_id_end
    value.logObjectEnd.timezone= directions.timezone_end
    value.relatedLogObjects= directions.related_last_mile_object_ids
    value.deliveryTimes= directions.extracted_delivery_times;

note left
--data-raw '{
    "routesUid": "dcde0682142ce1fb66b0c41b9c59c955",
    "isActive": true,
    "logObjectIdStart": {
    "objectId": "hub-05",
    "timezone": "UTC+3"
},
    "logObjectIdEnd": {
    "objectId": "hub-08",
    "timezone": "UTC+3"
},
    "relatedLogObjects": [
    "darkstore-003",
    "darkstore-007"
],
    "deliveryTimes": [
        {
            "dateStart": "2025-07-15T05:00:00",
            "dateEnd": "2025-07-16T05:00:00",
            "duration": 1440
        },
        {
            "dateStart": "2025-07-16T05:00:00",
            "dateEnd": "2025-07-17T05:00:00",
            "duration": 1440
        },
        {
            "dateStart": "2025-07-17T05:00:00",
            "dateEnd": "2025-07-18T05:00:00",
            "duration": 1440
        }
    ]
}'
endnote

:Вызвать API доставки
POST 'https://e-commerce-api/api/logisticService/v1/LogisticKafkaHttpProducer/sendOne'
    --header 'Kafka-Topic-Name: p75.frem.newOrderlogistic'
    --header 'Authorization: Basic PnJlZDpmcbVk'
    --header 'Content-Type: application/json';

if (Ответ успешный?) then (Да)
:Изменить статус отправленной записи
с CALCULATED на SENT;

endif
repeat while (Есть ли еще данные?)

:Удалить все записи
с is_active==false
и status==SENT;
stop

@enduml